root: true

extends:
  - eslint:recommended
  - prettier

env:
  es2021: true

parserOptions:
  ecmaVersion: latest
  sourceType: module

overrides:
  - files: ['*.ts', '*.tsx']
    extends:
      - plugin:@typescript-eslint/eslint-recommended
      - plugin:@typescript-eslint/recommended
    plugins:
      - '@typescript-eslint'
    parser: '@typescript-eslint/parser'
