name = "tinyfox-mastodon"
main = "src/index.ts"
compatibility_date = "2022-12-13"
node_compat = true
# minify = true

[triggers]
crons = ["30 * * * *"]

[vars]
BASE_URL = "https://botsin.space/"

# [secrets]
# CLIENT_KEY
# CLIENT_SECRET
# ACCESS_TOKEN
